ifeq ($(PARAM_FILE), ) 
    PARAM_FILE:=../Makefile.param
    include $(PARAM_FILE)
endif

all:
	@cd  ./common; make all

clean:
	@cd  ./common; make clean

install:
	@cd  ./common; make install

uninstall:
	@cd  ./common; make uninstall


